name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 7, 8]
        include:
          - os: ubuntu-latest
            node_version: 8
            ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 7
          - os: macos-latest
            node_version: 6
    runs-on: ${{ matrix.os }}
    env:
      UBUNTU_8: ${{ matrix.ubuntu_8 }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: After Setup-node node version
        run: |
          node -v
          echo $UBUNTU_8
          

    